DoSomething/LetsDoThis-Android

- app/src/main/java/org/dosomething/letsdothis/data/Kudo.java
- app/src/main/java/org/dosomething/letsdothis/network/DoSomethingAPI.java
- app/src/main/java/org/dosomething/letsdothis/network/models/RequestKudo.java
- app/src/main/java/org/dosomething/letsdothis/tasks/SubmitKudosTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/ReportBackDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/KudoClickListener.java
- app/src/main/res/layout/item_report_back_expanded.xml
- app/src/main/res/layout/kudos.xml
> Added Kudos enums,

- app/src/main/java/org/dosomething/letsdothis/network/models/ResponseAvatar.java
- app/src/main/java/org/dosomething/letsdothis/tasks/UploadAvatarTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/RegisterActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/AvatarChangeFragment.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/SettingsFragment.java
- app/src/main/res/layout/fragment_avatar_change.xml
- app/src/main/res/values/strings.xml
- Fixes the response to match a change on the API: `avatar` -> `photo`
- Upload the photo to Northstar if it's provided on user registration
- Adds an [intermediary screen](https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Settings/Photo%20Changer.png) after tapping "Change Photo" on the Settings screen
> Profile photo updates

- app/src/main/java/org/dosomething/letsdothis/data/Campaign.java
- app/src/main/java/org/dosomething/letsdothis/network/DoSomethingAPI.java
- app/src/main/java/org/dosomething/letsdothis/network/models/ResponseReportBackList.java
- app/src/main/java/org/dosomething/letsdothis/tasks/BaseReportBackListTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/IndividualCampaignReportBackList.java
- app/src/main/java/org/dosomething/letsdothis/tasks/InterestReportBackListTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/CampaignFragment.java
- app/src/main/res/layout/item_campaign.xml
- app/src/main/res/layout/item_campaign_large.xml
- app/src/main/res/layout/item_campaign_small.xml
- app/src/main/res/values/colors.xml
Primarily UI-related updates in the main feed.
- The feed of reportback photos in the main feed and in the campaign details feed queries for promoted photos first, then approved photos
- Campaigns in the main feed are displayed in alphabetical order within each tabbed group
- Added visual indicator in main feed for campaigns a user is signed up for
2.0.2
2.0.9
2.0.10
> Main feed updates

- app/src/main/java/org/dosomething/letsdothis/network/NetworkHelper.java
- app/src/main/java/org/dosomething/letsdothis/network/deserializers/ResponseCampaignDeserializer.java
- app/src/main/java/org/dosomething/letsdothis/network/models/ResponseCampaign.java
- app/src/main/java/org/dosomething/letsdothis/tasks/UpdateInterestGroupCampaignTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/CampaignFragment.java
- app/src/main/java/org/dosomething/letsdothis/utils/TimeUtils.java
- app/src/main/res/layout/item_campaign.xml
- app/src/main/res/layout/item_campaign_expired_large.xml
- app/src/main/res/layout/item_campaign_large.xml
- app/src/main/res/layout/item_campaign_small.xml
- app/src/main/res/layout/item_hub_expire.xml
- app/src/main/res/layout/lightning_button.xml
- app/src/main/res/values/strings.xml
Changes here are to a campaign's open view on the Main Feed.
- Sign up button ("Stop Being Bored") changes to "You're Doing This" if you've already signed up for the campaign
- Removed the Problem Fact section and moved the Call To Action tagline down from the image into where the Problem Fact used to be.
- The "expires in" label is now based off the `mobile_app.dates.end` field in the API response. Previously just assumed the campaigns would expire at the end of the month.
2.1.0
2.1.2
2.1.3
> Campaign open view updates

- app/src/main/java/org/dosomething/letsdothis/data/ReportBack.java
- app/src/main/java/org/dosomething/letsdothis/tasks/DbGetCampaignTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/ReportBackDetailsTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/GroupActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/ReportBackDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/ReportBackUploadActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/CampaignFragment.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/JoinGroupDialogFragment.java
- app/src/main/res/layout/item_report_back_expanded.xml
- User name (instead of id) and country location (instead of date submitted) now shown in reportback item view
- Roger added and used as the default profile photo
- Impact text "# of [noun] [verb]" added to the expanded reportback item view
- Kudos views removed from the UI
2.2.2
3.0.2
> Reportback Item View: kudos removed; name, location, impact added

- app/src/main/java/org/dosomething/letsdothis/data/Campaign.java
- app/src/main/java/org/dosomething/letsdothis/data/UserReportBack.java
- app/src/main/java/org/dosomething/letsdothis/network/models/ResponseUserCampaign.java
- app/src/main/java/org/dosomething/letsdothis/tasks/GetCurrentUserCampaignsTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/MainActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/ReplaceFragmentListener.java
- app/src/main/res/layout/item_hub_current_campaign.xml
- app/src/main/res/layout/item_hub_current_empty.xml
- app/src/main/res/layout/item_hub_expire.xml
- app/src/main/res/values/strings.xml
Cleans up the Hub UI to more closely match spec.
- Updated Hub view for when the user has not yet signed up for any campaign
- Displays reportback image when user's submitted a reportback. Displays an empty image view if the user has not yet submitted a reportback.
- Shows submitted reportback count and caption, if any
- Clicking on the campaign title in the Hub goes to that campaign's detail screen
5.0.2
5.0.3
5.0.4
5.0.6
5.0.7
> Hub updates

- app/src/main/java/org/dosomething/letsdothis/ui/fragments/SettingsFragment.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference_general.xml
- Removes Notifications segment
- Adds link to the bottom of the Settings screen to go to our campaign suggestion webpage
- Fixes "rate app" link for devices that don't have the market app (ex - emulator)
5.3.4
> Settings UI updates

- app/src/main/java/org/dosomething/letsdothis/tasks/BaseNetworkErrorHandlerTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/CampaignSignUpTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/ActionsFragment.java
- app/src/main/res/layout/activity_fragment_recycler.xml
- app/src/main/res/layout/fragment_actions.xml
- app/src/main/res/values/strings.xml
Adds more handling around no-internet-connection sort of scenarios.
The main feed will check if the device is online. If it's not, it'll show a [no connection view](https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Discovery/No%20Connection.png).
The retry button on that no connection view will refresh the view if the device comes back online.
Also changing the Toast message displayed on general network errors.
10.0.0, 10.0.1
> No internet connection handling

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/org/dosomething/letsdothis/data/CampaignActions.java
- app/src/main/java/org/dosomething/letsdothis/data/DatabaseHelper.java
- app/src/main/java/org/dosomething/letsdothis/network/models/RequestCampaignSignup.java
- app/src/main/java/org/dosomething/letsdothis/tasks/CampaignSignUpTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/DbGetCampaignTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/DbInterestGroupCampaignListTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/GetUserCampaignsTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/LoginTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/LogoutTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/RegisterTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/ReportbackUploadTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/UpdateInterestGroupCampaignTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/UploadAvatarTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/LoginActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/RegisterActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/CampaignFragment.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/SettingsFragment.java
- app/src/main/java/org/dosomething/letsdothis/utils/AppPrefs.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preference_general.xml
v1.0.0 release!
**Building**
The Gradle build config was modified a bit so that required resources wouldn't get removed during minifying and resource shrinking.
**Buggy campaign signups**
There's something buggy about the logic used to determine if a campaign signup was already done or not. For now, we're just gonna not use that logic and always send the request to the API.
**Cleanup on logout**
Due to the nature of how things were getting tested (single device, multiple users), some errors were seen that involved previous user data not being cleared out.
**Misc**
And then yea, just other various bug fixes, error handling and polish. Reading the commit messages might be the best way to get more details on what was done.
> Fixes to get us to v1.0.0

- .flowconfig
- .gitignore
- app/build.gradle
- app/src/main/java/org/dosomething/letsdothis/LDTApplication.java
- app/src/main/java/org/dosomething/letsdothis/react/CampaignNavigationModule.java
- app/src/main/java/org/dosomething/letsdothis/react/ConfigModule.java
- app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/MainActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/NewsFragment.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- index.android.js
- package.json
Building from the React Native prototype work, this PR gets the project setup to use React Native and gets the javascript code to match as closely as possible to the current state of things on iOS as of https://github.com/DoSomething/LetsDoThis-iOS/commit/64e15d0fc78bf55eb0e956896da078fbec00826f
Following along with the notes in the commits is probably the best way to follow along with the changes being made. Some highlights:
- 57a38cb primarily contains project changes
- index.android.js is where all the ReactNative js code currently lives
- CampaignNavigationModule and ConfigModule are two custom native modules that needed to be created to handle some native behavior  - launching a new activity and getting the appropriate news url depending on build type
Touches on aspects of #137 but …
> Foundation of React Native news feed

- app/react/index.android.js
The background color in the header of news posts differs depending on the cause name.
Heavily based off of the changes in https://github.com/DoSomething/LetsDoThis-iOS/pull/776
> Adjusts header colors based on cause title

- app/react/index.android.js
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dosomething/letsdothis/react/WebViewModule.java
- app/src/main/java/org/dosomething/letsdothis/ui/WebViewActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/NewsFragment.java
- app/src/main/res/layout/activity_web_view.xml
- app/src/main/res/values-w820dp/dimens.xml
Adds a new React Native module (WebViewModule) to open a new activity (WebViewActivity) styled with the LDT toolbar. Previously, we used React Native's `IntentAndroid`, but this would take us outside of the app.
> Displays linked news feed content within in-app webview

- app/src/main/java/org/dosomething/letsdothis/network/NorthstarAPI.java
- app/src/main/java/org/dosomething/letsdothis/network/models/ResponseLogin.java
- app/src/main/java/org/dosomething/letsdothis/network/models/ResponseRegister.java
- app/src/main/java/org/dosomething/letsdothis/network/models/ResponseUser.java
- app/src/main/java/org/dosomething/letsdothis/tasks/BaseRegistrationTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/GetUserTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/LoginTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/LogoutTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/RegisterTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/UpdateUserTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
Updates the Northstar API calls in response to the changes made here: DoSomething/northstar#268
- Login: `POST auth/token`
- Logout: `POST auth/invalidate`
- Register: `POST auth/register`
- Get current user profile: `GET /profile`
- Update current user profile: `POST /profile`
Closes #135
> Northstar API updates

- app/react/newsfeed-post.js
- app/src/main/java/org/dosomething/letsdothis/react/CampaignNavigationModule.java
- app/src/main/java/org/dosomething/letsdothis/react/ShareIntentModule.java
- app/src/main/java/org/dosomething/letsdothis/react/WebViewModule.java
- app/src/main/java/org/dosomething/letsdothis/ui/CauseActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/WebViewActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/NewsFragment.java
- app/src/main/java/org/dosomething/letsdothis/utils/AnalyticsUtils.java
Adds GA screen tracking to the news feed and web view. Also tracks events for actions that can be taken on news feed posts: share, read article and take action button.
Closes #146
> Google Analytics tracking added to News Feed

- README.md
- app/src/main/res/values/strings.xml
What the title says.
Closes #176
> Changing app name and references from Let's Do This to DoSomething

- app/src/main/java/org/dosomething/letsdothis/ui/SettingsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/SettingsFragment.java
- app/src/main/res/values/strings.xml
Shows ProgressDialog on logout. Removes title from ProgressDialog in Hub (to match its usage elsewhere).
> Minor ProgressDialog polish

- app/src/main/java/org/dosomething/letsdothis/network/NorthstarAPI.java
- app/src/main/java/org/dosomething/letsdothis/network/models/RequestReportback.java
- app/src/main/java/org/dosomething/letsdothis/tasks/ReportbackUploadTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/PhotoCropActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/RegisterActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/ReportBackUploadActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/AvatarChangeFragment.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
Submitting reportbacks from the Hub should now be working.
> Working reportback from the Hub

- app/src/main/java/org/dosomething/letsdothis/network/models/ResponseSubmitReportBack.java
- app/src/main/java/org/dosomething/letsdothis/tasks/CampaignDetailsTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/ReportbackUploadTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/MainActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
- app/src/main/res/values/strings.xml
Yea, basically gets report back submissions from the campaign detail screen working along with the handling of the state of that screen after submission.
> Fixes reportbacks from the campaign page

- app/src/main/java/org/dosomething/letsdothis/network/NorthstarAPI.java
- app/src/main/java/org/dosomething/letsdothis/network/models/ResponseUser.java
- app/src/main/java/org/dosomething/letsdothis/tasks/GetProfileSignupsTask.java
- app/src/main/java/org/dosomething/letsdothis/tasks/GetProfileTask.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
- app/src/main/res/values/strings.xml
Recent changes to the Hub and API had previously broken the public profile view of other users. This PR provides a fix. It basically looks the same except the "Prove It" and "Share" buttons are hidden.
> Public Profile fix

- README.md
- app/.gitignore
- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/org/dosomething/letsdothis/ui/StartActivity.java
Adds New Relic monitoring which now gives us fancy tracking like this...
It's worth noting that the New Relic app token is not being committed. In order to build after this commit, devs will need to update their local secret.properties and add a newrelic.properties file.
Closes #142
> Adds New Relic agent for monitoring

- app/src/main/java/org/dosomething/letsdothis/data/Causes.java
- app/src/main/java/org/dosomething/letsdothis/ui/CauseActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/MainActivity.java
- app/src/main/res/layout/activity_intro.xml
- app/src/main/res/layout/item_cause_list.xml
- app/src/main/res/values/strings.xml
Primarily just updates the copy to adhere to the current design. Also includes a couple fixes:
- The relationships cause previously incorrectly displayed the animals cause description
- The CauseActivity screen displayed a title in the toolbar that was incorrectly styled (wrong font, size and camel-cased)
Closes #170
> Copy updates!

- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
- app/src/main/res/layout/item_campaign_details.xml
The main thing is it gets rid of the yellow slanted background that was in the previous design. And then just a couple more text style and spacing tweaks on that screen.
Closes #207
> Campaign screen style updates

- app/src/main/java/org/dosomething/letsdothis/network/NorthstarAPI.java
- app/src/main/java/org/dosomething/letsdothis/tasks/GetProfileSignupsTask.java
It's not required, but is a future-proofing thing since there will probably be plans to require it later.
Closes #215
> Adds Session header to GET /signups?user=id call

- app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
- app/src/main/res/values/strings.xml
Displays progress dialog popup when signup and and share tasks are in progress. Displays a "Please wait..." message.
Closes #208
> ProgressDialog on Signup and Share

- app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
- app/src/main/res/values/strings.xml
Shows Snackbar error messages if you try to take action on a campaign that's either an SMS game or is closed.
Closes #224
> SMS Game/Closed campaign handling

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/RegisterActivity.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/AvatarChangeFragment.java
- app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
We're using a new photo cropping library: https://github.com/jdamcd/android-crop
It gives the user a little more control over how they can crop their photo. All areas of the app that do photo cropping have been updated to use the new method.
**TODO for later:** There's a lot of similar code across the different areas that could likely be consolidated into a single spot.
Closes #125
> New photo cropping!

- app/src/main/java/org/dosomething/letsdothis/tasks/CampaignDetailsTask.java
- app/src/main/res/layout/item_campaign_details.xml
- incorrectly set the mHasError property in the CampaignDetailsTask to true
- fixed the 'Do This' label that incorrectly had left/right padding applied to it
- fixed the background colors on the campaign detail screen
> Fixes to campaign task and style

- app/src/main/java/org/dosomething/letsdothis/ui/fragments/AvatarChangeFragment.java
- app/src/main/res/values/strings.xml
The crash came from tapping the Save Photo button before a photo was first selected.
https://fabric.io/do-something/android/apps/org.dosomething.letsdothis/issues/56e740c0ffcdc04250d5ecbd
> Fixes crash when there's an error selecting a photo for your profile

- app/src/main/java/org/dosomething/letsdothis/tasks/BaseRegistrationTask.java
Provides the user with more specific error messages if there is a problem during registration. The fix was to update the data structure of the expected response which changed in the API.
> Registration Error Handling

- app/src/main/java/org/dosomething/letsdothis/ui/fragments/AvatarChangeFragment.java
Relevant Trello card: https://trello.com/c/hwNBpFYc/120-build-1-1-0-profile-image-doesn-t-set-when-you-take-a-photo
> Fixes issue where avatar photo doesn't change

- app/react/newsfeed-post.js
What the title says. It looks like this...
Closes #269
> Changes link-to-article copy to 'View original story'
