app/src/main/java/org/dosomething/letsdothis/data/User.java
app/src/main/java/org/dosomething/letsdothis/network/models/RequestCampaignSignup.java
app/src/main/java/org/dosomething/letsdothis/network/models/RequestReportback.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseAvatar.java
app/src/main/java/org/dosomething/letsdothis/tasks/ReportbackUploadTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/UploadAvatarTask.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/SettingsFragment.java

- `"android"` is included as the `source` on user registration, signup, and reportback requests. We were already doing it for signups and just needed to add to the models for requests sent on registration and reportback.
- Avatar wrapper and crash fixes: ResponseAvatar, UploadAvatarTask, SettingsFragment
Through the app, registered a new user on staging. Signed up for and submitted a reportback for a campaign. Verified relevant `source` fields were populated on the staging db.
Closes #73

'source' param included in registration and reportback requests

---

app/src/main/java/org/dosomething/letsdothis/data/User.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseLogin.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseRegister.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseUserUpdate.java
app/src/main/java/org/dosomething/letsdothis/tasks/BaseRegistrationTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/LoginTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/RegisterTask.java
app/src/main/java/org/dosomething/letsdothis/ui/LoginActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/RegisterActivity.java
app/src/main/res/drawable/edittext_error_background.xml
app/src/main/res/values/strings.xml

- Adds input validation + error stylings to login and register forms before sending.
- Sends `source=android` as a property when registering a new user
- Sends current configured country code on login and registration
- If on login, the user's `country` has already been set and is the same as the phone's current configuration, then no user update request will be sent.
- The country is also determined based on the user's phone's configuration. It's more immediate, doesn't require any special permission and covers a large majority of our use cases. Where it fails is if users are hopping from one country to another, or users who are in one country but configure their phones to use the locale of a different country.
- **ResponseUserUpdate:** This response has been fixed on the server to …

Login/Reg error styling + source and country in request data

---

app/src/main/java/org/dosomething/letsdothis/network/NorthstarAPI.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseCampaign.java
app/src/main/java/org/dosomething/letsdothis/ui/LoginActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
app/src/main/res/layout/item_campaign_details.xml
app/src/main/res/values/strings.xml

Primarily, this does a little clean up in the campaign detail view. The problem fact section is removed, the call to action tagline is brought down below the image, and the solution copy and support fields pull their data from `raw` instead of `formatted`.
A couple other non-campaign detail related changes:
- The login calls have the `Accept: application/json` header added. When login fails, the logs showed that the response was an html page. If ever we needed to do better handling of login errors based on the API response, it'll be easier working with it as json - also saves us from unnecessary log spam.
- The login form also used to show by default a "touch@lab.co" account. This is removed in anticipation of debug builds going out to more test phones.
3.0.0

Campaign detail view update

---

app/src/main/java/org/dosomething/letsdothis/tasks/GetUserCampaignsTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/GetUserTask.java
app/src/main/java/org/dosomething/letsdothis/ui/ReportBackDetailsActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/CampaignFragment.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/NotificationsFragment.java
app/src/main/res/layout/item_hub_public_empty.xml
app/src/main/res/values/strings.xml

Other user profiles are now viewable by clicking on either their name or profile photo from the gallery in the campaign details screen or in an individual reportback detail screen.
- Public Hub view is modified to hide action buttons and image container when no reportback photo is available
- Added a separate empty view for public profiles
- GetCurrentUserCampaignsTask was modified to a more generic GetUserCampaignsTask. A user id now needs to be provided to the task
- A user's photo (if any) in the campaign details gallery should now display correctly
2.2.4
3.0.3
5.2.0

Public Profile Hub

---

app/src/main/java/org/dosomething/letsdothis/tasks/CampaignSignUpTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/GetUserCampaignsTask.java
app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
app/src/main/res/layout/item_campaign_details.xml

The campaign detail screen (for a campaign the user hasn't signed up for) can be reached from the reportbacks of other users. Changes here add design and support for that screen in its pre-signup state.
https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Discovery/Campaign%20Presignup.png
- Hiding solution views
- Functional sign up button
- Progress bar while sign up is in progress
Other things that come with those changes:
- The actions for the current user's campaign actions are now saved locally whenever GetUserCampaignsTask is run for that user
- CampaignSignUpTask now posts an event to the default EventBus when it completes
3.0.0c

Campaign Detail pre-signup state

---

app/src/main/java/org/dosomething/letsdothis/data/InterestGroup.java
app/src/main/java/org/dosomething/letsdothis/network/DoSomethingAPI.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseTaxonomyTerm.java
app/src/main/java/org/dosomething/letsdothis/tasks/GetInterestGroupTitleTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/UpdateInterestGroupCampaignTask.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/ActionsFragment.java
app/src/main/res/values/strings.xml

- Retrieves campaigns by the current date instead of just whatever had `mobile_app=1`set. This will make for easier management of the content on the app side from month to month. Also, ideally puts the app in a place where we don't really have to worry about displaying campaigns that are closed.
- The group names displayed in the main feed are now also retrieved from the server. The new `GetInterestGroupTitleTask` handles the retrieval.
The `taxonomy_term` endpoint used to get the tag names needs to be enabled. Even after manually enabling it, it seems like it gets automatically disabled every time there's a deploy to the server.
https://github.com/DoSomething/phoenix/issues/5342 was added to resolve this
2.0.12

Campaigns queried by date. Group titles retrieved from server.

---

app/src/main/java/org/dosomething/letsdothis/tasks/CampaignSignUpTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/GetInterestGroupTitleTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/UploadAvatarTask.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/CampaignFragment.java
app/src/main/res/values/strings.xml

Fixes for crashes that were found in v0.0.4. A couple were null pointer exceptions that just needed a null check.
Another involved mismatched data between Northstar and Phoenix. This theoretically shouldn't happen in practice. It only seemed to happen in this case because we were manually deleting data on Northstar staging to test stuff.
That being said, errors can happen, and a bunch of the changes here are to better handle errors that can and probably will arise.
If the `taxonomy_term` endpoint isn't available for one reason or another, this previously used to crash because the error wasn't handled. Now we're showing a Toast message.
Same deal here but with profile photo uploading.
We similarly don't want to crash on any errors that happen here. The task's error status is saved along …

Crash fixes + error handling on main feed

---

.gitignore
README.md
app/build.gradle
app/src/main/java/org/dosomething/letsdothis/data/InterestGroup.java
app/src/main/java/org/dosomething/letsdothis/network/DoSomethingAPI.java
app/src/main/java/org/dosomething/letsdothis/network/NetworkHelper.java
app/src/main/java/org/dosomething/letsdothis/network/NorthstarAPI.java

This PR essentially adds support to use Thor as another server to query against.
Doing this resulted in a bit of refactoring to how URLs and interest group IDs get assigned. Instead of a **secrets.xml** file to keep our secret values, this PR now necessitates that app id and api key information be included in a **secrets.properties** file that doesn't get committed into the repository.
**build.gradle**
A new "internal" build variant was added with the intent of it being used for internal/DS test builds. The build file reads values out of **secrets.properties** and assigns them to auto-generated string resource values. In this way we can set the different URLs and IDs that need to be used in the different server environments.
This can be seen in practice in **InterestGroup.java** for …

Modified build config

---

app/src/main/java/org/dosomething/letsdothis/network/models/ResponseRbData.java
app/src/main/java/org/dosomething/letsdothis/tasks/RbShareDataTask.java
app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/GroupActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
app/src/main/res/values/strings.xml

There's a Share Photo button that shows up when you've reported back on a campaign. It lets you share the photo you reported back with to your social networks.
This had previously been implemented to only share the image. The changes in this PR additionally set the default message which includes the reported quantity and action noun and verbs.
- **ResponseRbData.RBData** - in addition to the renaming, the `quantity` field is also added here so that we're able to access that later when we build the default message
- **HubFragment.java and CampaignDetailsActivity.java** - The changes here are pretty straightforward in order to allow text to be included in the Intent along with the photo. The type was change to `text/plain` and `Intent.EXTRA_SUBJECT` and `Intent.EXTRA_TEXT` were added to the …

Sets the default message for the "Share Photo" action

---

app/src/main/java/org/dosomething/letsdothis/data/User.java
app/src/main/java/org/dosomething/letsdothis/ui/ReportBackDetailsActivity.java
app/src/main/res/layout/item_report_back_expanded.xml

Correctly displays the profile photo of the user who submitted the reportback on the reportback detail screen. Previously it would also display Roger.
- **item_report_back_expanded.xml**: While the photo's being downloaded, it would show Roger for a split second. Removing it here so it doesn't show.
- **ReportBackDetailsActivity.java**: Uses `photo` instead of `avatarPath`. Also loads up Roger if there is no provided photo.
- **User.java**: This class doesn't seem to be meant to be used as an API response handler, but in the case of ReportBackDetailsTask, it does. And instead of the photo being available under `avatarPath` it's in `photo`. Pretty confusing having both of them in that class, so we'll probably want to fix this up later to consolidate the two vars.

Fix to properly display profile photo on reportback details screen

---

app/src/main/java/org/dosomething/letsdothis/tasks/UpdateInterestGroupCampaignTask.java
app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java

- Gracefully handles errors that could happen if there was slowness or other sorts of server errors while trying to pull campaign data for the main feed. Basically just throws a Toast error and doesn't crash.
- Handles any errors that might come from the "Share Photo" process. If any required data like the photo or campaign info wasn't successfully retrieved, we just remove that info from the share, but still allow the share intent to be open. Otherwise, people would just be tapping on the "Share Photo" button and nothing would happen.
- **UpdateInterestGroupCampaignTask.java**: This just lets the parent class handle the error. And that class does `return true` in all cases, so we won't crash.
- **CampaignDetailsActivity.java** and **HubFragment.java**: This is the Share Photo handling …

Crash fixes

---

app/src/main/java/org/dosomething/letsdothis/ui/fragments/SettingsFragment.java
app/src/main/java/org/dosomething/letsdothis/utils/AnalyticsUtils.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preference_general.xml

It adds a link in the Settings screen to our app feedback google form. Also...
- removes the "We'll never interrupt you to ask for ratings." line
- New Google Analytic tracking event. The feedback form added here will use the "tap on feedback form" event, and the UGC ideas form will use "tap on ideas form" for its event string
What the Setting screen now looks like on Android.

Adds link to feedback form in Settings

---

app/build.gradle
app/src/main/java/org/dosomething/letsdothis/tasks/CampaignSignUpTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/LogoutTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/ReportbackUploadTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/UpdateInterestGroupCampaignTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/UploadAvatarTask.java
app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/CampaignFragment.java
app/src/main/res/layout/activity_fragment_recycler.xml
app/src/main/res/values/strings.xml

- Basic Toast confirmation messages on user actions: campaign signup, reportback and changing profile photo
- Changed logic on how campaign data is retrieved. Used to pull from local db first, but now pulls from server. There's probably some optimization that can be done here, but it'll at least fix up problems we would see otherwise with campaign content not being updated even if it has been on the server.
- Fail whale type of screen added when there's an error (server or network) pulling campaign data from the server
- LogoutTask mini-refactor - should fix problems that could come from failed logouts and then trying to log back in

v0.0.8 merge

---

app/src/main/java/org/dosomething/letsdothis/network/NetworkHelper.java
app/src/main/java/org/dosomething/letsdothis/network/PhoenixAPI.java
app/src/main/java/org/dosomething/letsdothis/tasks/BaseReportBackListTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/CampaignDetailsTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/GetInterestGroupTitleTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/GetUserCampaignsTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/GroupTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/InvitesTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/ReportBackDetailsTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/UpdateInterestGroupCampaignTask.java
app/src/main/java/org/dosomething/letsdothis/ui/MainActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/InvitesFragment.java

Functionally nothing should've changed. This should just rename the DoSomethingAPI service and references to it to PhoenixAPI. It matches how we talk about the API internally and clarifies that it's specifically Phoenix and not a general DoSomething API.
Run on an emulator against staging. Ensured all areas that the app makes calls to Phoenix behave normally:
- **main activity feed** with interest group names, campaigns per group and gallery of reportback photos
- **individual campaign detail page** with campain info and gallery of reportback photos
Closes #126

Rename DoSomethingAPI to PhoenixAPI

---

app/src/main/java/org/dosomething/letsdothis/tasks/CampaignSignUpTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/ReportbackUploadTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/UploadAvatarTask.java
app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/SettingsActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/AvatarChangeFragment.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/CampaignFragment.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
app/src/main/res/layout/activity_fragment_quickreturn_recycler.xml
app/src/main/res/layout/activity_settings.xml
app/src/main/res/layout/fragment_avatar_change.xml
app/src/main/res/layout/fragment_recycler.xml

Snackbarrrrr confirmation for campaign signup, campaign reportback and profile photo change.
- Toast messages used to be hidden in the Tasks. We're able to take this logic out of there into the specific Fragment or Activity that the messages should show up in now.
- Anywhere a `android.support.design.widget.CoordinatorLayout`widget has gotten added into xml is where a SnackBar is getting used.
- Also added a ProgressBar to the AvatarChangeFragment while a photo is being uploaded.
Closes #130

Snackbar confirmation messages

---

app/src/main/java/org/dosomething/letsdothis/ui/MainActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/DrawerListAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/CauseListFragment.java
app/src/main/res/layout/item_hub_expire.xml
app/src/main/res/values/strings.xml

Minor Hub changes towards #169.
- Primarily removing unused code that was meant for the abandoned concept of 12 campaigns that would expire at the end of each month.
- Fixed link for button in an empty Hub view to point to the cause list screen.
- Changed campaign header labels in the Hub to static text instead of displaying the number of days left until campaigns would expire.

Hub modifications

---

app/build.gradle
app/src/main/java/org/dosomething/letsdothis/network/NetworkHelper.java
app/src/main/java/org/dosomething/letsdothis/utils/AnalyticsUtils.java

- Internal release builds will now point to Thor again
- Excludes 64-bit binaries from the build because React Native didn't provide one. This would manifest itself in crashes on 64-bit phones that try to open the news feed
- Crash fix when going to any cause screen
Closes #151 (hopefully)
Closes #173

Thor. x64. Crash fix.

---

app/src/main/java/org/dosomething/letsdothis/ui/LoginActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/RegisterActivity.java
app/src/main/res/values/strings.xml

Displays a ProgressDialog while a sign in or register call is in progress. This should help avoid bugs that could come along when the user tries to resubmit and sign in or register request while one is already going.
Closes #179

Display a ProgressDialog while a sign in or register call is in progress

---

app/build.gradle
app/react/newsfeed-view.js
package.json

Upgrades the React Native version we're using from 0.17 to 0.19.
And fixes one crash that surfaced after the upgrade.
This is one potential step towards fixing #157. There's a proguard fix in React Native 0.19, but this PR doesn't yet get around to fully fixing the release builds.

React update 0.19

---

app/react/newsfeed-view.js

It's what it looked like before we started correctly using the `styleAttr`.

Changes news feed loading icon to Normal from Small

---

app/src/main/java/org/dosomething/letsdothis/network/NorthstarAPI.java
app/src/main/java/org/dosomething/letsdothis/network/models/RequestCampaignSignup.java
app/src/main/java/org/dosomething/letsdothis/network/models/RequestReportback.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseCampaignSignUp.java
app/src/main/java/org/dosomething/letsdothis/tasks/CampaignSignUpTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/RegisterTask.java
app/src/main/java/org/dosomething/letsdothis/ui/LoginActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/MainActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/RegisterActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/StartActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
app/src/main/res/values/strings.xml

Fixes campaign signups to work with the updated API.
**Commits:**
- Fixes the campaign signup API call
- also changes the source value for register, signup and reportback calls from letsdothis_android to mobileapp_android
- Updates local cache of a user's campaign actions when opening up the Hub
- Get user's campaign actions from server and cache to local after login or register
Fixes #191

Fixes campaign signups

---

app/build.gradle
app/src/main/AndroidManifest.xml

Updates Crashlytics to 2.5.5 and adds api key to the manifest.
Definitely tried hiding the Crashlytics API key in our local secrets.properties file and loading it in through Gradle, but it wasn't working for some reason. It feels ok enough exposing this key. If it somehow does get abused, we can change and find a better way of handling it then

Crashlytics fix

---

app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
app/src/main/res/layout/item_hub_current_empty.xml
app/src/main/res/values/strings.xml

- Displays the "empty view" Hub layout if the user has no current signups
- Ensures the "empty view" doesn't display when viewing public / other user profiles
- Doesn't show the "Actions I've Done" label if there are no reportbacks
Fixes #202

Displays an empty view in the Hub if user has no signups

---

app/src/main/java/org/dosomething/letsdothis/data/Campaign.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseCampaign.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseCampaignList.java
app/src/main/java/org/dosomething/letsdothis/tasks/GetUserCampaignsTask.java
app/src/main/java/org/dosomething/letsdothis/tasks/UpdateInterestGroupCampaignTask.java
app/src/main/java/org/dosomething/letsdothis/ui/CauseActivity.java

So sms_game campaigns shouldn't be viewable on the app. Also filters out campaigns that are not currently 'active', unless it's a campaign that should show up in a user's reportback profile.
Closes #197

Filters out campaigns that are not type 'campaign'

---

app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java

Fixes crash in the Hub when a campaign doesn't return a campaign_run object.
Fixes #212

Hub crash fix

---

app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java

Closes #218 
Turns out we already were querying for `approved` and `promoted` status. We currently query for promoted first, and then approved. There was a bug though were particularly short lists wouldn't make the second call for approved ones. This should fix that.

Fixes issue where some campaigns didn't show approved reportback items

---

app/src/main/java/org/dosomething/letsdothis/network/models/ResponseReportBackList.java
app/src/main/java/org/dosomething/letsdothis/tasks/BaseReportBackListTask.java
app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java

If a user somehow gets to a campaign screen for a closed campaign, we hide the Sign Up / Prove It button from the view. They could potentially get there through other user profiles or the news feed or... I don't know, maybe there are other ways.
Plus a couple unrelated fixes because why not: 
- Fixes the response data structure to a `GET reportback-items` call. The `pagination` object is now wrapped inside a `meta` object.
- Fixes bug where a campaign state would incorrectly be shown to a user as if they signed into it. This would occur after the user would visit the profile of another user who had signed up for that campaign.
Closes #219
cc: @aaronschachter

Prevents signup for closed campaigns

---

app/src/main/java/org/dosomething/letsdothis/ui/ReportBackUploadActivity.java
app/src/main/res/values/strings.xml

Prevents a reportback caption with emojis or special symbols.
This also sets the error message on the relevant EditText boxes instead of showing it as a Toast message. This matches how we do error message handling on the registration and login forms.
Closes #180

Prevents a reportback caption with emojis or special symbols

---

app/src/main/java/org/dosomething/letsdothis/tasks/BaseRegistrationTask.java
app/src/main/java/org/dosomething/letsdothis/ui/RegisterActivity.java

- The API response for registration errors has changed, so this update is to match those changes.
- Spaces after an email would also incorrectly trigger it as an invalid email. The fix added here is just to do a trim before running validation. We already have it do a trim before submitting the registration request.
Closes #227

Fixes registration error handling

---

app/src/main/java/org/dosomething/letsdothis/network/PhoenixAPI.java
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseCampaignList.java
app/src/main/java/org/dosomething/letsdothis/tasks/GetCampaignsByCauseTask.java
app/src/main/java/org/dosomething/letsdothis/ui/CauseActivity.java
app/src/main/res/layout/item_cause_header.xml

- Fixes a crash on the Cause screen when there's no network connection
- Fixes an issue where only the first 25 campaigns under a cause would be loaded into the list
- Changes the background color of the cause header to a solid color instead of using a pattern
Closes #231 
Closes #233

Cause screen fixes

---

app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
app/src/main/res/layout/fragment_register_login.xml
app/src/main/res/layout/item_hub_profile.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

The number of signups and reportbacks are now displayed in the top section of the profile.
Other changes:
- the user's name is taken out of the top section and moved into the toolbar
- totally unrelated to the Hub: new line added to the login/reg onboarding screen
Closes #174

Adds user stats to the profile header

---

app/src/main/java/org/dosomething/letsdothis/react/ConfigModule.java

Also changes the endpoint to `/api/get_posts` to match the iOS implementation.
Closes #239

Updates News Feed API URL to get the last 50 posts

---

app/src/main/java/org/dosomething/letsdothis/ui/adapters/CampaignDetailsAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
app/src/main/java/org/dosomething/letsdothis/utils/ViewUtils.java
app/src/main/res/values/strings.xml

Changes first name to 'Doer' if the `first_name` field is an email.
It's been seen to happen in a couple rare cases so we're doing this to prevent private information from being shown. Logic to do this now is also moved to a static function in ViewUtils.
And unrelated, but also removed unused references that used to be needed for an old design.
https://github.com/DoSomething/LetsDoThis-iOS/pull/933

Sanitizes first name when displayed

---

app/src/main/java/org/dosomething/letsdothis/ui/ReportBackUploadActivity.java
app/src/main/res/layout/activity_register.xml
app/src/main/res/layout/activity_report_back_upload.xml
app/src/main/res/layout/activity_signin.xml

Adds ime options to input fields on the registration, login and reportback forms in the app. Also sets the `inputType` where appropriate. Adding these makes it easier for the user to fill out forms.
The work done in ReportBackUploadActivity.java was needed (as opposed to being able to do it strictly through XML) in order to create a multiline EditText field that also had the imeOption "actionNext" set.
Closes #245

EditText polish

---

app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java

This fixes this sort of thing from happening:
If a null User is passed onto the adapter, the logic was such that it'd add on a new user row instead of replacing the current one. This was easily replicable by leaving the app from the Hub and opening it back up into the Hub with the network connection turned off.

Fixes duplicate user stat views in the Hub

---

app/src/main/java/org/dosomething/letsdothis/tasks/CampaignDetailsTask.java
app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
app/src/main/res/values/strings.xml

When this occurs we'll display a Toast error message and finish out of the CampaignDetailsActivity. In the future, we'll want to display an error view.
Fixes #254

Fixes crash on network error during CampaignDetailsTask

---

app/src/main/java/org/dosomething/letsdothis/ui/CampaignDetailsActivity.java
app/src/main/res/values/strings.xml

Some of the photos displayed in a campaign gallery come with a null user profile object in the API response. If we don't handle cases like these, the HubFragment code will default to showing the logged-in user profile.
Relevant Trello card: https://trello.com/c/Diwg0vrf/124-build-1-1-0-profile-redirecting-to-your-profile

Displays popup error message if user tries to click into a null profile

---

app/src/main/res/values/strings.xml

"This experience can only be done through text messaging. Text APP to 38383 to get started!"
This is the message that will now display if you try to signup for an SMS game.
Closes #264

Changes the SMS game error message

---

app/src/main/java/org/dosomething/letsdothis/tasks/ProfileReportbackShareTask.java
app/src/main/java/org/dosomething/letsdothis/ui/adapters/HubAdapter.java
app/src/main/java/org/dosomething/letsdothis/ui/fragments/HubFragment.java
app/src/main/res/values/strings.xml

Fixes a crash that could come from sharing a reportback with invalid data.
We do validation on the data in [ProfileReportbackShareTask](https://github.com/DoSomething/LetsDoThis-Android/compare/master...issue265#diff-d785bc399ae18633eee9c3af7dc5266fR68) and throw a custom error if anything fails. What the user will see is a Toast error message instead of a crash.
We also prevent the Share Intent from starting if there was an error in loading the reportback data.
Fixes #265

Handles errors that could come during the sharing of a reportback

---

app/build.gradle
app/src/main/java/org/dosomething/letsdothis/network/models/ResponseCampaign.java

- Campaign 5769 needed a hardcoded sponsor logo, so this does that.
- Also updates version code to 4 and name to 1.1.2 for submission update to the Play Store
Behold:
cc: @aaronschachter @lkpttn

Hardcodes the sponsor logo for campaign 5769
